global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'llm_ops'
    static_configs:
      - targets: ['localhost:8000'] # Replace with the endpoint of your metrics server
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
