llm:
  provider: openai
  model_name: gpt-4
  temperature: 0.7
  max_tokens: 1000

retriever:
  type: pinecone
  api_key: ${PINECONE_API_KEY} # Retrieved from environment
  environment: ${PINECONE_ENV} # Retrieved from environment
  index_name: llm-retrieval-index

langsmith:
  api_key: ${LANGSMITH_API_KEY} # Retrieved from environment

chains:
  - name: summarization_chain
    steps:
      - retriever
      - llm
  - name: question_answering_chain
    steps:
      - retriever
      - llm

memory:
  type: vectorstore
  capacity: 500
