chains:
  default:
    verbose: true
    memory:
      type: "ConversationBufferMemory"
      max_token_limit: 2000
    
embeddings:
  model: "text-embedding-ada-002"
  chunk_size: 1000
  chunk_overlap: 200 