apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: llm-pipeline-
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: preprocess
        template: preprocess
      - name: train
        template: train
  - name: preprocess
    container:
      image: my-docker-repo/preprocess:latest # TODO: change to the actual image
      command: ["python", "/app/preprocess.py"] # TODO: change to the actual entrypoint
  - name: train
    container:
      image: my-docker-repo/train:latest # TODO: change to the actual image name
      command: ["python", "/app/train.py"] # TODO: change to the actual entrypoint