name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy Terraform
      working-directory: infra/terraform
      run: |
        terraform init
        terraform validate
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan

    - name: Deploy AWS Lambda
      working-directory: infra/lambda
      run: |
        zip function.zip preprocess.data.py
        aws lambda update-function-code --function-name preprocess-data --zip-file fileb://function.zip

    - name: Notify Success
      uses: slackapi/slack-github-action@v1.23.0
      with:
        slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
        text: 'Deployment to AWS was successful!'
